###
GET https://syukatu-app-new-backend.vercel.app

### 
POST https://syukatu-app-new-backend.vercel.app/api/auth/register
Content-Type: application/json

{
  "username": "dkaoda",
  "email": "ryuhosoy@yahoo.co.jp",
  "password": "555555"
}

### 
POST https://syukatu-app-new-backend.vercel.app/api/posts
Content-Type: application/json

{
  "userId": "ryuhei",
  "companyName": "aa"
}

###
POST https://syukatu-app-new-backend.vercel.app/api/auth/login
Content-Type: application/json

{
  "email": "ryuhosoy@yahoo.co.jp",
  "password": "55555555"
}

###
PUT  https://syukatu-app-new-backend.vercel.app/api/users/66de9c21217f1ab8682480ef
Content-Type: application/json

{
  "userId": "66de9c21217f1ab8682480ef",
  "username": "ryuhosoy更新2"
}

###
DELETE https://syukatu-app-new-backend.vercel.app/api/users/66e13341f99ede0fcbc7b2e9
Content-Type: application/json

{
  "userId": "66e13341f99ede0fcbc7b2e9"
}

###
GET  https://syukatu-app-new-backend.vercel.app/api/users/66de8be96220fa7ae95133f4

###
PUT  https://syukatu-app-new-backend.vercel.app/api/users/66e12cf2cbf45d65dad040ad/follow
Content-Type: application/json

{
  "userId": "66e13341f99ede0fcbc7b2e9"
}

###
PUT  https://syukatu-app-new-backend.vercel.app//api/users/66e12cf2cbf45d65dad040ad/unfollow
Content-Type: application/json

{
  "userId": "66e13341f99ede0fcbc7b2e9"
}