name: Run Python Scripts

on:
  schedule:
    - cron: "0 18 * * *" # UTCで午後6時（日本時間で午前3時）
  workflow_dispatch: # 手動トリガーも設定

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 必要なPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 必要な依存関係をインストール
        pip install -r py-requirements.txt

    - name: Run fetcherInfoDuringLikeSpan.py
      run: python py/fetcherInfoDuringLikeSpan.py

    - name: Run fetcherAllCompanies.py
      run: python py/fetcherAllCompanies.py
